### ISSUE TITLE
Fix inertia matrices for all links

### ISSUE THREAD

**Issue by DarthBubi** [pilsbot/pilsbot_description#1]
Wrong inertia matrices and masses prevents the bot from moving correctly in simulation. This can be fixed by weighing the real components or at least give an educated guess about their mass. The corresponding inertia matrix can then be easily calculated according to [this ](https://en.wikipedia.org/wiki/List_of_moments_of_inertia#List_of_3D_inertia_tensors) at least for our simple shapes.

**Comment by Cirromulus** [comment]
How would the motors be calculated, as they are self powered?
Or do we just weigh them in stand-still?

**Comment by DarthBubi** [comment]
We just assume the moments for inert masses. Everything else would be over modeling, and I don't think even commercial robots are modeled that way.
